notifications:
  email:
    on_success: never
    on_failure: always

language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - "5.6"

env:
  - DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE

matrix:
  include:
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=master
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=master
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat

env:
  - DB=pgsql MOODLE_VERSION=master TAG=@block_fbcomments
  - DB=pgsql MOODLE_VERSION=MOODLE_32_STABLE TAG=@block_fbcomments
  - DB=pgsql MOODLE_VERSION=MOODLE_31_STABLE TAG=@block_fbcomments
  - DB=pgsql MOODLE_VERSION=MOODLE_30_STABLE TAG=@block_fbcomments

matrix:

  fast_finish: true

  exclude:
    - php: 7.1
      env: DB=pgsql MOODLE_VERSION=MOODLE_30_STABLE TAG=@block_fbcomments
    - env: DB=pgsql MOODLE_VERSION=MOODLE_31_STABLE TAG=@block_fbcomments
      php: 7.1
    - env: DB=pgsql MOODLE_VERSION=MOODLE_32_STABLE TAG=@block_fbcomments
      php: 5.6
    - env: DB=pgsql MOODLE_VERSION=master TAG=@block_fbcomments
      php: 5.6

install:
  - git clone git://github.com/moodle/moodle ../moodle && cd ../moodle
  - git checkout $MOODLE_VERSION
  - sudo apt-get update > /dev/null
  - mv ../moodle-block_fbcomments ./blocks/fbcomments
  - composer self-update
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get -y update
  - sudo apt-get install -y --force-yes php-curl php-pgsql php-intl php-curl php-dev php-gd php-mcrypt php-tidy php-xmlrpc
  - cp config-dist.php config.php
  - sh -c "sed -i -e s/\'password\'/\'\'/ -e s%example.com/moodle%moodle.travis/moodle% -e s%/home/example%$HOME% -e 's%\(\$CFG.*bht\)%\n\1%' -e 's%\(\$CFG.*phpunit\)%\n\1%' -e 's%\(\$CFG.*behat_wwwroot.*http://127\)%\n\1%' -e s%127.0.0.1/moodle%localhost:8000% config.php"
  - cat config.php
  - sh -c "psql -c 'create database moodle;' -U postgres"
  - sh -c "sed -i s/\'username\'/\'postgres\'/ config.php"
  - mkdir -m777 $HOME/moodledata
  - mkdir -m777 $HOME/bht_moodledata

before_script:
  - php admin/tool/behat/cli/init.php
  - "(php -S localhost:8000 &) 2> /dev/null > /dev/null"
  - "wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar"
  - "(java -jar selenium-server-standalone-2.53.1.jar &) 2> /dev/null > /dev/null"
  # Give time to selenium to start up.
  - sleep 10

script:
  - vendor/bin/behat --config /home/travis/bht_moodledata/behat/behat.yml --tags $TAG